In [1]:
import numpy as np
import pandas as pd

## NUMPY

In [4]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [5]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
np.random.normal(10, 4, (3,4)) 

array([[ 5.61086178, 11.46484518,  9.75938192, 14.13848188],
       [18.26595289, 14.22062042, 11.488083  ,  9.05991602],
       [12.10077249,  8.56396464,  9.10160155,  8.34202015]])

In [11]:
np.random.randint(0, 10, (3,3))

array([[2, 7, 1],
       [0, 3, 5],
       [8, 1, 0]])

#### NOT
* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [13]:
np.arange(0, 31, 3).shape

(11,)

### Birleştirme

In [14]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

### Fancy Index

In [16]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [17]:
v[1]

3

In [18]:
v[3]

9

In [19]:
al_getir = [1,3,5]
v[al_getir]

array([ 3,  9, 15])

In [21]:
#iki boyutta fancy
m = np.arange(9).reshape((3,3))
satir = np.array([0,1])
sutun = np.array([1,2])
m[satir,sutun]

array([1, 5])

In [22]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
m[0, [1,2]] # 0,1 ile 0,2 yi döndürür.

array([1, 2])

In [39]:
m[0:, [1,2]] #tüm satırları ve 1.ve 2. sütunları döndürür

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
m[m < 5]

array([0, 1, 2, 3, 4])

## PANDAS

#### Pandas DataFrame

In [42]:
l = [1,2,39,67,90]
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [43]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [47]:
df.columns = ("deg1","deg2","deg3")
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [48]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

sozluk = {"var1": s1, "var2": s2, "var3": s3}

df2 = pd.DataFrame(sozluk)
df2

var1  var2  var3
0     8     8     8
1     3     4     7
2     4     0     5
3     5     9     8
4     9     1     4

In [50]:
df2.index

RangeIndex(start=0, stop=5, step=1)

In [52]:
df2.index = ["a","b","c","d","e"]
df2

var1  var2  var3
a     8     8     8
b     3     4     7
c     4     0     5
d     5     9     8
e     9     1     4

In [58]:
#Fancy
l = ["c","e"]
df2.drop(l, axis = 0)

var1  var2  var3
a     8     8     8
b     3     4     7
d     5     9     8

In [62]:
df2["c":"e"]

var1  var2  var3
c     4     0     5
d     5     9     8
e     9     1     4

## loc ve iloc

In [68]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    11    15     4
1    11     6     8
2    26    24    22
3     8    12    28
4    25     8    20
5    22     6    29
6    26     2    22
7    26    15    17
8    22    29    13
9    24    23     3

In [69]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.
df.loc[0:3]

var1  var2  var3
0    11    15     4
1    11     6     8
2    26    24    22
3     8    12    28

In [70]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.
df.iloc[0:3]

var1  var2  var3
0    11    15     4
1    11     6     8
2    26    24    22

In [71]:
df.iloc[0,0]

11

In [72]:
df.iloc[:3,:2]

var1  var2
0    11    15
1    11     6
2    26    24

In [73]:
df.loc[0:3, "var3"]

0     4
1     8
2    22
3    28
Name: var3, dtype: int64

In [75]:
df.iloc[0:4]["var3"]

0     4
1     8
2    22
3    28
Name: var3, dtype: int64

In [76]:
df[0:2][["var1","var2"]]

var1  var2
0    11    15
1    11     6

In [77]:
df.var1

0    11
1    11
2    26
3     8
4    25
5    22
6    26
7    26
8    22
9    24
Name: var1, dtype: int64

In [78]:
df[df.var1 > 15]

var1  var2  var3
2    26    24    22
4    25     8    20
5    22     6    29
6    26     2    22
7    26    15    17
8    22    29    13
9    24    23     3

In [80]:
df[(df.var1 > 15) & (df.var3 < 5)] #ikisini de parantez içine alınması lazım

var1  var2  var3
9    24    23     3

In [81]:
df.loc[(df.var1 > 15), ["var1","var2"]]

var1  var2
2    26    24
4    25     8
5    22     6
6    26     2
7    26    15
8    22    29
9    24    23

In [82]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
2    26    24
4    25     8
5    22     6
6    26     2
7    26    15
8    22    29
9    24    23

## Birleştirme işlemleri

In [83]:
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    19    18     3
1    25    14    12
2     2    15    28
3     4     4    13
4    15     8    12

In [84]:
df2 = df1 + 99
df2

var1  var2  var3
0   118   117   102
1   124   113   111
2   101   114   127
3   103   103   112
4   114   107   111

In [85]:
pd.concat([df1,df2])

var1  var2  var3
0    19    18     3
1    25    14    12
2     2    15    28
3     4     4    13
4    15     8    12
0   118   117   102
1   124   113   111
2   101   114   127
3   103   103   112
4   114   107   111

In [86]:
pd.concat([df1,df2], ignore_index = True)

var1  var2  var3
0    19    18     3
1    25    14    12
2     2    15    28
3     4     4    13
4    15     8    12
5   118   117   102
6   124   113   111
7   101   114   127
8   103   103   112
9   114   107   111

In [87]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [89]:
df2.columns = ["var1","var2","deg3"]
df2

var1  var2  deg3
0   118   117   102
1   124   113   111
2   101   114   127
3   103   103   112
4   114   107   111

In [90]:
pd.concat([df1, df2])

/tmp/ipykernel_26275/69889205.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  pd.concat([df1, df2])


deg3  var1  var2  var3
0    NaN    19    18   3.0
1    NaN    25    14  12.0
2    NaN     2    15  28.0
3    NaN     4     4  13.0
4    NaN    15     8  12.0
0  102.0   118   117   NaN
1  111.0   124   113   NaN
2  127.0   101   114   NaN
3  112.0   103   103   NaN
4  111.0   114   107   NaN

In [91]:
pd.concat([df1, df2], join = "inner")

var1  var2
0    19    18
1    25    14
2     2    15
3     4     4
4    15     8
0   118   117
1   124   113
2   101   114
3   103   103
4   114   107

In [92]:
pd.concat([df1, df2], join_axes = [df2.columns], ignore_index=True)

/tmp/ipykernel_26275/1880629355.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  pd.concat([df1, df2], join_axes = [df2.columns], ignore_index=True)


var1  var2   deg3
0    19    18    NaN
1    25    14    NaN
2     2    15    NaN
3     4     4    NaN
4    15     8    NaN
5   118   117  102.0
6   124   113  111.0
7   101   114  127.0
8   103   103  112.0
9   114   107  111.0

In [93]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [94]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [95]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [96]:
pd.merge(df1, df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

## Gruplama işlemleri

In [97]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [98]:
df.groupby("gruplar")

In [99]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [100]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [102]:
import seaborn as sns
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [103]:
df.groupby("method")

In [106]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [107]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

## İleri Toplulaştırma İşlemleri

In [109]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [112]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A               16        181
B               17        182
C               66        651

In [111]:
#agg
df.groupby("gruplar").agg([min, np.median, max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10     16  22       100    181  262
B              11     17  23       111    182  253
C              33     66  99       333    651  969

In [113]:
df.groupby("gruplar").agg({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [120]:
#filter
def filter_func(x):
    return x["degisken1"].std() > 9

In [121]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [122]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [123]:
#apply
df.groupby("gruplar").apply(np.mean)

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

## Pivot Tablolar

In [125]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [126]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [130]:
titanic.groupby(["sex","class"])[["survived"]].agg("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [131]:
#Pivot table ile
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [132]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [133]:
titanic.pivot_table("survived", ["sex", age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663